//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class b3752Entities : DbContext
    {
        public b3752Entities()
            : base("name=b3752Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogsTag> BlogsTags { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<CurriculumVitae> CurriculumVitaes { get; set; }
        public DbSet<CurriculumVitaeContact> CurriculumVitaeContacts { get; set; }
        public DbSet<CurriculumVitaeHobby> CurriculumVitaeHobbies { get; set; }
        public DbSet<CurriculumVitaeLinguisticLanguage> CurriculumVitaeLinguisticLanguages { get; set; }
        public DbSet<CurriculumVitaeOperatingSystem> CurriculumVitaeOperatingSystems { get; set; }
        public DbSet<CurriculumVitaeProfessionalSkillsCircleDiagram> CurriculumVitaeProfessionalSkillsCircleDiagrams { get; set; }
        public DbSet<CurriculumVitaeProgrammingLanguage> CurriculumVitaeProgrammingLanguages { get; set; }
        public DbSet<CurriculumVitaeQuality> CurriculumVitaeQualities { get; set; }
        public DbSet<CurriculumVitaeScholarship> CurriculumVitaeScholarships { get; set; }
        public DbSet<CurriculumVitaeSoftware> CurriculumVitaeSoftwares { get; set; }
        public DbSet<CurriculumVitaeWorkExperience> CurriculumVitaeWorkExperiences { get; set; }
        public DbSet<Home> Homes { get; set; }
        public DbSet<Licence> Licences { get; set; }
        public DbSet<Reference> References { get; set; }
        public DbSet<Tag> Tags { get; set; }
    }
}
