//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogsTags
    {
        public System.Guid ID { get; set; }
        public System.Guid BlogID { get; set; }
        public System.Guid TagID { get; set; }
    
        public virtual Blogs Blogs { get; set; }
        public virtual Tags Tags { get; set; }
    }
}
