//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.BlogsTags = new HashSet<BlogsTag>();
        }
    
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyingDate { get; set; }
        public string Body { get; set; }
        public System.Guid Admin { get; set; }
    
        public virtual Admin Admin1 { get; set; }
        public virtual ICollection<BlogsTag> BlogsTags { get; set; }
    }
}
