//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Licences = new HashSet<Licence>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string EMail { get; set; }
    
        public virtual ICollection<Licence> Licences { get; set; }
    }
}
