//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumVitae
    {
        public CurriculumVitae()
        {
            this.CurriculumVitaeContacts = new HashSet<CurriculumVitaeContact>();
            this.CurriculumVitaeHobbies = new HashSet<CurriculumVitaeHobby>();
            this.CurriculumVitaeLinguisticLanguages = new HashSet<CurriculumVitaeLinguisticLanguage>();
            this.CurriculumVitaeOperatingSystems = new HashSet<CurriculumVitaeOperatingSystem>();
            this.CurriculumVitaeProfessionalSkillsCircleDiagrams = new HashSet<CurriculumVitaeProfessionalSkillsCircleDiagram>();
            this.CurriculumVitaeProgrammingLanguages = new HashSet<CurriculumVitaeProgrammingLanguage>();
            this.CurriculumVitaeQualities = new HashSet<CurriculumVitaeQuality>();
            this.CurriculumVitaeScholarships = new HashSet<CurriculumVitaeScholarship>();
            this.CurriculumVitaeSoftwares = new HashSet<CurriculumVitaeSoftware>();
            this.CurriculumVitaeWorkExperiences = new HashSet<CurriculumVitaeWorkExperience>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public byte[] Image { get; set; }
        public string Lang { get; set; }
    
        public virtual ICollection<CurriculumVitaeContact> CurriculumVitaeContacts { get; set; }
        public virtual ICollection<CurriculumVitaeHobby> CurriculumVitaeHobbies { get; set; }
        public virtual ICollection<CurriculumVitaeLinguisticLanguage> CurriculumVitaeLinguisticLanguages { get; set; }
        public virtual ICollection<CurriculumVitaeOperatingSystem> CurriculumVitaeOperatingSystems { get; set; }
        public virtual ICollection<CurriculumVitaeProfessionalSkillsCircleDiagram> CurriculumVitaeProfessionalSkillsCircleDiagrams { get; set; }
        public virtual ICollection<CurriculumVitaeProgrammingLanguage> CurriculumVitaeProgrammingLanguages { get; set; }
        public virtual ICollection<CurriculumVitaeQuality> CurriculumVitaeQualities { get; set; }
        public virtual ICollection<CurriculumVitaeScholarship> CurriculumVitaeScholarships { get; set; }
        public virtual ICollection<CurriculumVitaeSoftware> CurriculumVitaeSoftwares { get; set; }
        public virtual ICollection<CurriculumVitaeWorkExperience> CurriculumVitaeWorkExperiences { get; set; }
    }
}
