//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumVitaeWorkExperience
    {
        public System.Guid ID { get; set; }
        public string Company { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public string Positions { get; set; }
        public string Tasks { get; set; }
        public System.Guid CurriculumVitaeID { get; set; }
    
        public virtual CurriculumVitae CurriculumVitae { get; set; }
    }
}
