//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG_Warrior_Software_Official_Webpage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        public System.Guid ID { get; set; }
        public string SoftwareName { get; set; }
        public System.Guid ClientID { get; set; }
        public string TradeMark { get; set; }
        public string Copyright { get; set; }
        public System.Guid Licence1 { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
